from fpdf import FPDF

class GradeCardPDF(FPDF):
    def header(self):
        # IGNOU Logo (optional) - you can add path to an image if available
        # self.image('ignou_logo.png', 10, 8, 25)
        self.set_font("Arial", "B", 16)
        self.cell(0, 10, "INDIRA GANDHI NATIONAL OPEN UNIVERSITY", 0, 1, 'C')
        self.set_font("Arial", "B", 14)
        self.cell(0, 10, "BCA_NEWOL Consolidated Grade Card", 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.cell(0, 10, "Generated by IGNOU CBCS System", 0, 0, 'C')

# Create PDF
pdf = GradeCardPDF()
pdf.add_page()
pdf.set_auto_page_break(auto=True, margin=15)

# Student Info
pdf.set_font("Arial", "", 12)
pdf.cell(0, 8, "Name: Aj Anam", 0, 1)
pdf.cell(0, 8, "Enrollment No.: XXXXXXXX", 0, 1)
pdf.cell(0, 8, "Program: BCA_NEWOL", 0, 1)
pdf.cell(0, 8, "Semester: 1 & 2", 0, 1)
pdf.ln(5)

# Table Header
pdf.set_font("Arial", "B", 11)
pdf.set_fill_color(200, 200, 200)  # Light gray background
headers = ["Course", "Credits", "Assignment", "TEE", "Weighted %", "Letter", "GP", "Credits×GP"]
col_widths = [25, 15, 20, 15, 25, 20, 15, 25]

for i, header in enumerate(headers):
    pdf.cell(col_widths[i], 8, header, 1, 0, 'C', fill=True)
pdf.ln()

# Table Data
pdf.set_font("Arial", "", 11)
courses = [
    ["BCS012",4,85,69,73.8,"A",8,32],
    ["BCS111",4,80,56,63.2,"B+",7,28],
    ["BCSL013",2,90,98,95.6,"O",10,20],
    ["BEGLA136",4,75,65,68.0,"A",8,32],
    ["BEVAE181",4,77,86,83.3,"A+",9,36],
    ["FEG02",4,74,62,65.6,"A",8,32],
    ["MCS201",4,80,61,66.7,"A",8,32],
    ["MCS202",4,85,70,74.5,"A",8,32],
    ["MCS203",4,86,54,63.6,"B+",7,28],
    ["MCSL204",2,90,88,88.6,"O",10,20],
    ["MCSL205",2,80,96,91.2,"O",10,20]
]

# Alternate row coloring
fill = False
for row in courses:
    for i, item in enumerate(row):
        pdf.cell(col_widths[i], 8, str(item), 1, 0, 'C', fill=fill)
    pdf.ln()
    fill = not fill

pdf.ln(5)
pdf.set_font("Arial", "B", 12)
pdf.cell(0, 8, "Total Credits: 40", 0, 1)
pdf.cell(0, 8, "Total Credits×GP: 328", 0, 1)
pdf.cell(0, 8, "CGPA: 8.20", 0, 1)
pdf.cell(0, 8, "Equivalent Percentage: 82.0%", 0, 1)
pdf.ln(5)
pdf.set_font("Arial", "", 11)
pdf.multi_cell(0, 8, "Remarks: Very Good / Excellent performance. Outstanding scores in practical courses: BCSL013, MCSL204, MCSL205. Successfully completed all courses in Semesters 1 & 2.")

# Save PDF
pdf.output("BCA_NEWOL_GradeCard_OfficialStyle.pdf")
print("Official-style PDF generated: BCA_NEWOL_GradeCard_OfficialStyle.pdf")
